-- ==============================================================================
-- FINFLOW — SCHEMA SUPABASE POSTGRESQL COM ROW LEVEL SECURITY (RLS)
-- Execute este script no SQL Editor do seu projeto Supabase (painel web)
-- ==============================================================================

-- 1. Tabela de Categorias
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL DEFAULT auth.uid(),
    name TEXT NOT NULL,
    type TEXT CHECK (type IN ('income', 'expense')) DEFAULT 'expense',
    color TEXT DEFAULT '#17191c',
    icon TEXT DEFAULT 'tag',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabela de Transações (Receitas e Despesas)
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL DEFAULT auth.uid(),
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    description TEXT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    type TEXT CHECK (type IN ('income', 'expense')) NOT NULL,
    date DATE NOT NULL,
    payment_method TEXT DEFAULT 'pix',
    status TEXT CHECK (status IN ('paid', 'pending')) DEFAULT 'paid',
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabela de Orçamentos e Limites Mensais
CREATE TABLE IF NOT EXISTS public.budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL DEFAULT auth.uid(),
    category_id BIGINT REFERENCES public.categories(id) ON DELETE CASCADE NOT NULL,
    monthly_limit NUMERIC(12, 2) NOT NULL CHECK (monthly_limit > 0),
    month TEXT NOT NULL, -- Formato: 'YYYY-MM'
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_user_category_month UNIQUE (user_id, category_id, month)
);

-- ==============================================================================
-- 4. ROW LEVEL SECURITY (RLS) — ISOLAMENTO TOTAL NATIVO NO BANCO DE DADOS
-- Cada usuário só tem permissão para LER, INSERIR, ATUALIZAR e DELETAR seus próprios dados.
-- Nenhum usuário consegue ver registros de outro mesmo via SQL direto na API.
-- ==============================================================================

-- Habilitar RLS em todas as tabelas
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.budgets ENABLE ROW LEVEL SECURITY;

-- Políticas para Categorias
DROP POLICY IF EXISTS "Categorias: isolamento total por usuario" ON public.categories;
CREATE POLICY "Categorias: isolamento total por usuario"
    ON public.categories
    FOR ALL
    TO authenticated
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Políticas para Transações
DROP POLICY IF EXISTS "Transacoes: isolamento total por usuario" ON public.transactions;
CREATE POLICY "Transacoes: isolamento total por usuario"
    ON public.transactions
    FOR ALL
    TO authenticated
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Políticas para Orçamentos
DROP POLICY IF EXISTS "Orcamentos: isolamento total por usuario" ON public.budgets;
CREATE POLICY "Orcamentos: isolamento total por usuario"
    ON public.budgets
    FOR ALL
    TO authenticated
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- ==============================================================================
-- 5. TRIGGER AUTOMÁTICO: Popula Categorias Padrão para Novos Usuários
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user_categories()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.categories (user_id, name, type, color, icon) VALUES
        (NEW.id, 'Alimentação & Mercado', 'expense', '#5d2a1a', 'utensils'),
        (NEW.id, 'Moradia & Contas', 'expense', '#17191c', 'home'),
        (NEW.id, 'Transporte & Combustível', 'expense', '#777b86', 'car'),
        (NEW.id, 'Saúde & Cuidados', 'expense', '#5d2a1a', 'heart'),
        (NEW.id, 'Lazer & Cultura', 'expense', '#979799', 'smile'),
        (NEW.id, 'Educação & Livros', 'expense', '#17191c', 'book'),
        (NEW.id, 'Compras Pessoais', 'expense', '#777b86', 'shopping-bag'),
        (NEW.id, 'Serviços & Assinaturas', 'expense', '#a3a6af', 'credit-card'),
        (NEW.id, 'Salário & Remuneração', 'income', '#17191c', 'briefcase'),
        (NEW.id, 'Rendimentos & Dividendos', 'income', '#5d2a1a', 'trending-up'),
        (NEW.id, 'Freelance & Extras', 'income', '#777b86', 'code'),
        (NEW.id, 'Outras Receitas', 'income', '#979799', 'plus-circle');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user_categories();

-- Índices para consultas ultra rápidas
CREATE INDEX IF NOT EXISTS idx_transactions_user_date ON public.transactions (user_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_categories_user ON public.categories (user_id);
CREATE INDEX IF NOT EXISTS idx_budgets_user_month ON public.budgets (user_id, month);
